version: '3.8'

services:
  api_server:
    build: .
    container_name: rayanx_backend_core
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb_node:27017/rayanx_mdm
      - REDIS_URL=redis://redis_node:6379
    depends_on:
      - mongodb_node
      - redis_node
    restart: always

  mongodb_node:
    image: mongo:6.0
    container_name: mdm_production_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  redis_node:
    image: redis:7.0-alpine
    container_name: mdm_production_redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  mongo_data:
